name: tests

on:
  push:
    branches: [trunk]
  pull_request:

jobs:
  plenary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - uses: actions/checkout@v4
        with:
          repository: nvim-lua/plenary.nvim
          path: deps/plenary.nvim

      - name: Run tests
        run: |
          nvim --headless -u tests/minimal_init.lua \
            -c "PlenaryBustedDirectory tests {minimal_init='tests/minimal_init.lua'}" \
            -c "qa!"
